const COLORS = [
	{ value: 'amber', label: 'Amber' },
	{ value: 'amethyst', label: 'Amethyst' },
	{ value: 'apricot', label: 'Apricot' },
	{ value: 'aqua', label: 'Aqua' },
	{ value: 'beige', label: 'Beige' },
	{ value: 'black', label: 'Black' },
	{ value: 'blue', label: 'Blue' },
	{ value: 'blush', label: 'Blush' },
	{ value: 'brass', label: 'Brass' },
	{ value: 'brick', label: 'Brick' },
	{ value: 'bronze', label: 'Bronze' },
	{ value: 'brown', label: 'Brown' },
	{ value: 'burgundy', label: 'Burgundy' },
	{ value: 'canary', label: 'Canary' },
	{ value: 'carmine', label: 'Carmine' },
	{ value: 'cerulean', label: 'Cerulean' },
	{ value: 'charcoal', label: 'Charcoal' },
	{ value: 'chartreuse', label: 'Chartreuse' },
	{ value: 'cherry', label: 'Cherry' },
	{ value: 'chocolate', label: 'Chocolate' },
	{ value: 'cobalt', label: 'Cobalt' },
	{ value: 'copper', label: 'Copper' },
	{ value: 'coral', label: 'Coral' },
	{ value: 'cream', label: 'Cream' },
	{ value: 'crimson', label: 'Crimson' },
	{ value: 'cyan', label: 'Cyan' },
	{ value: 'denim', label: 'Denim' },
	{ value: 'eggplant', label: 'Eggplant' },
	{ value: 'emerald', label: 'Emerald' },
	{ value: 'fawn', label: 'Fawn' },
	{ value: 'fern', label: 'Fern' },
	{ value: 'forest_green', label: 'Forest Green' },
	{ value: 'fuchsia', label: 'Fuchsia' },
	{ value: 'garnet', label: 'Garnet' },
	{ value: 'gold', label: 'Gold' },
	{ value: 'grape', label: 'Grape' },
	{ value: 'gray', label: 'Gray' },
	{ value: 'green', label: 'Green' },
	{ value: 'honey', label: 'Honey' },
	{ value: 'hot_pink', label: 'Hot Pink' },
	{ value: 'hunter_green', label: 'Hunter Green' },
	{ value: 'indigo', label: 'Indigo' },
	{ value: 'ivory', label: 'Ivory' },
	{ value: 'jade', label: 'Jade' },
	{ value: 'khaki', label: 'Khaki' },
	{ value: 'lavender', label: 'Lavender' },
	{ value: 'lemon', label: 'Lemon' },
	{ value: 'lilac', label: 'Lilac' },
	{ value: 'lime', label: 'Lime' },
	{ value: 'magenta', label: 'Magenta' },
	{ value: 'marigold', label: 'Marigold' },
	{ value: 'maroon', label: 'Maroon' },
	{ value: 'mauve', label: 'Mauve' },
	{ value: 'midnight_blue', label: 'Midnight Blue' },
	{ value: 'mint', label: 'Mint' },
	{ value: 'moss', label: 'Moss' },
	{ value: 'mustard', label: 'Mustard' },
	{ value: 'navy', label: 'Navy' },
	{ value: 'ochre', label: 'Ochre' },
	{ value: 'olive', label: 'Olive' },
	{ value: 'orange', label: 'Orange' },
	{ value: 'orchid', label: 'Orchid' },
	{ value: 'peach', label: 'Peach' },
	{ value: 'periwinkle', label: 'Periwinkle' },
	{ value: 'pine', label: 'Pine' },
	{ value: 'pink', label: 'Pink' },
	{ value: 'plum', label: 'Plum' },
	{ value: 'powder_blue', label: 'Powder Blue' },
	{ value: 'pumpkin', label: 'Pumpkin' },
	{ value: 'purple', label: 'Purple' },
	{ value: 'raspberry', label: 'Raspberry' },
	{ value: 'red', label: 'Red' },
	{ value: 'rose', label: 'Rose' },
	{ value: 'royal_blue', label: 'Royal Blue' },
	{ value: 'ruby', label: 'Ruby' },
	{ value: 'rust', label: 'Rust' },
	{ value: 'sage', label: 'Sage' },
	{ value: 'salmon', label: 'Salmon' },
	{ value: 'scarlet', label: 'Scarlet' },
	{ value: 'seafoam', label: 'Seafoam' },
	{ value: 'sienna', label: 'Sienna' },
	{ value: 'silver', label: 'Silver' },
	{ value: 'sky_blue', label: 'Sky Blue' },
	{ value: 'slate', label: 'Slate' },
	{ value: 'steel_blue', label: 'Steel Blue' },
	{ value: 'tan', label: 'Tan' },
	{ value: 'tangerine', label: 'Tangerine' },
	{ value: 'taupe', label: 'Taupe' },
	{ value: 'teal', label: 'Teal' },
	{ value: 'terracotta', label: 'Terracotta' },
	{ value: 'turquoise', label: 'Turquoise' },
	{ value: 'umber', label: 'Umber' },
	{ value: 'vermilion', label: 'Vermilion' },
	{ value: 'violet', label: 'Violet' },
	{ value: 'watermelon', label: 'Watermelon' },
	{ value: 'white', label: 'White' },
	{ value: 'wine', label: 'Wine' },
	{ value: 'yellow', label: 'Yellow' }
];
export async function get_colors(type_ahead) {
	if ('string' === typeof type_ahead && type_ahead.length > 2) {
		return COLORS.filter((color) => color.label.toLowerCase().startsWith(type_ahead.toLowerCase()));
	}
	return [];
}
