export interface Color {
	name: string;
	value: string;
}

const COLORS: readonly Color[] = [
	{ value: 'amber', name: 'Amber' },
	{ value: 'amethyst', name: 'Amethyst' },
	{ value: 'apricot', name: 'Apricot' },
	{ value: 'aqua', name: 'Aqua' },
	{ value: 'beige', name: 'Beige' },
	{ value: 'black', name: 'Black' },
	{ value: 'blue', name: 'Blue' },
	{ value: 'blush', name: 'Blush' },
	{ value: 'brass', name: 'Brass' },
	{ value: 'brick', name: 'Brick' },
	{ value: 'bronze', name: 'Bronze' },
	{ value: 'brown', name: 'Brown' },
	{ value: 'burgundy', name: 'Burgundy' },
	{ value: 'canary', name: 'Canary' },
	{ value: 'carmine', name: 'Carmine' },
	{ value: 'cerulean', name: 'Cerulean' },
	{ value: 'charcoal', name: 'Charcoal' },
	{ value: 'chartreuse', name: 'Chartreuse' },
	{ value: 'cherry', name: 'Cherry' },
	{ value: 'chocolate', name: 'Chocolate' },
	{ value: 'cobalt', name: 'Cobalt' },
	{ value: 'copper', name: 'Copper' },
	{ value: 'coral', name: 'Coral' },
	{ value: 'cream', name: 'Cream' },
	{ value: 'crimson', name: 'Crimson' },
	{ value: 'cyan', name: 'Cyan' },
	{ value: 'denim', name: 'Denim' },
	{ value: 'eggplant', name: 'Eggplant' },
	{ value: 'emerald', name: 'Emerald' },
	{ value: 'fawn', name: 'Fawn' },
	{ value: 'fern', name: 'Fern' },
	{ value: 'forest_green', name: 'Forest Green' },
	{ value: 'fuchsia', name: 'Fuchsia' },
	{ value: 'garnet', name: 'Garnet' },
	{ value: 'gold', name: 'Gold' },
	{ value: 'grape', name: 'Grape' },
	{ value: 'gray', name: 'Gray' },
	{ value: 'green', name: 'Green' },
	{ value: 'honey', name: 'Honey' },
	{ value: 'hot_pink', name: 'Hot Pink' },
	{ value: 'hunter_green', name: 'Hunter Green' },
	{ value: 'indigo', name: 'Indigo' },
	{ value: 'ivory', name: 'Ivory' },
	{ value: 'jade', name: 'Jade' },
	{ value: 'khaki', name: 'Khaki' },
	{ value: 'lavender', name: 'Lavender' },
	{ value: 'lemon', name: 'Lemon' },
	{ value: 'lilac', name: 'Lilac' },
	{ value: 'lime', name: 'Lime' },
	{ value: 'magenta', name: 'Magenta' },
	{ value: 'marigold', name: 'Marigold' },
	{ value: 'maroon', name: 'Maroon' },
	{ value: 'mauve', name: 'Mauve' },
	{ value: 'midnight_blue', name: 'Midnight Blue' },
	{ value: 'mint', name: 'Mint' },
	{ value: 'moss', name: 'Moss' },
	{ value: 'mustard', name: 'Mustard' },
	{ value: 'navy', name: 'Navy' },
	{ value: 'ochre', name: 'Ochre' },
	{ value: 'olive', name: 'Olive' },
	{ value: 'orange', name: 'Orange' },
	{ value: 'orchid', name: 'Orchid' },
	{ value: 'peach', name: 'Peach' },
	{ value: 'periwinkle', name: 'Periwinkle' },
	{ value: 'pine', name: 'Pine' },
	{ value: 'pink', name: 'Pink' },
	{ value: 'plum', name: 'Plum' },
	{ value: 'powder_blue', name: 'Powder Blue' },
	{ value: 'pumpkin', name: 'Pumpkin' },
	{ value: 'purple', name: 'Purple' },
	{ value: 'raspberry', name: 'Raspberry' },
	{ value: 'red', name: 'Red' },
	{ value: 'rose', name: 'Rose' },
	{ value: 'royal_blue', name: 'Royal Blue' },
	{ value: 'ruby', name: 'Ruby' },
	{ value: 'rust', name: 'Rust' },
	{ value: 'sage', name: 'Sage' },
	{ value: 'salmon', name: 'Salmon' },
	{ value: 'scarlet', name: 'Scarlet' },
	{ value: 'seafoam', name: 'Seafoam' },
	{ value: 'sienna', name: 'Sienna' },
	{ value: 'silver', name: 'Silver' },
	{ value: 'sky_blue', name: 'Sky Blue' },
	{ value: 'slate', name: 'Slate' },
	{ value: 'steel_blue', name: 'Steel Blue' },
	{ value: 'tan', name: 'Tan' },
	{ value: 'tangerine', name: 'Tangerine' },
	{ value: 'taupe', name: 'Taupe' },
	{ value: 'teal', name: 'Teal' },
	{ value: 'terracotta', name: 'Terracotta' },
	{ value: 'turquoise', name: 'Turquoise' },
	{ value: 'umber', name: 'Umber' },
	{ value: 'vermilion', name: 'Vermilion' },
	{ value: 'violet', name: 'Violet' },
	{ value: 'watermelon', name: 'Watermelon' },
	{ value: 'white', name: 'White' },
	{ value: 'wine', name: 'Wine' },
	{ value: 'yellow', name: 'Yellow' }
];

export async function get_colors(type_ahead: string): Promise<Color[]> {
	if (type_ahead.length > 2) {
		return COLORS.filter((color) => color.name.toLowerCase().startsWith(type_ahead.toLowerCase()));
	}
	return [];
}
